apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: {{ $.Values.email }}
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key
    solvers:
      - selector: {}
        dns01:
          route53:
            region: {{ $.Values.aws.region }}
            hostedZoneID: {{ $.Values.dns.hostedZoneID }}
