apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-cert
  namespace: istio-system
spec:
  secretName: ingress-cert
  commonName: "{{ $.Values.dns.commonName }}"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
  - "{{ $.Values.dns.dnsNames }}"
