apiVersion: v1
kind: Service
metadata:
  name: health-endpoint
  namespace: istio-system
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: health-endpoint
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
