apiVersion: v1
kind: ConfigMap
metadata:
  name: mongod-conf
  namespace: {{ required "mongodb.namespace is required in chart values" .Values.mongodb.namespace }}

data:
  automation-mongod.conf: |
    net:
      bindIp: 0.0.0.0
      port: 27017
    replication:
      replSetName: standalone-mongodb
    security:
      authorization: enabled
      keyFile: /var/lib/mongodb-mms-automation/authentication/keyfile
    setParameter:
      authenticationMechanisms: SCRAM-SHA-256
    storage:
      dbPath: /data
      engine: wiredTiger
      wiredTiger:
        engineConfig:
          journalCompressor: zlib

