apiVersion: apps/v1
kind: Deployment
metadata:
  name: standalone-mongodb-1-deployment
  namespace: {{ required "mongodb.namespace is required in chart values" .Values.mongodb.namespace }}

  labels:
    app: standalone-mongodb-1

spec:
  replicas: 1
  selector:
    matchLabels:
      app: standalone-mongodb-1
  template:
    metadata:
      labels:
        app: standalone-mongodb-1
    spec:
      nodeSelector:
        topology.kubernetes.io/zone: {{ required "mongodb.availability_zone_2 is required in chart values" .Values.mongodb.availability_zone_2 }}

      containers:
      - command:
        - /bin/sh
        - -c
        - |2+

          tail -F /var/log/mongodb-mms-automation/mongodb.log > /dev/stdout &

          # start mongod with this configuration
          exec mongod -f /opt/automation-mongod.conf;

        env:
        - name: AGENT_STATUS_FILEPATH
          value: /healthstatus/agent-health-status.json

        image: docker.io/mongo:4.4.13
        imagePullPolicy: IfNotPresent
        name: mongod
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: "6"
            memory: 16G
          requests:
            cpu: "6"
            memory: 16G
        #securityContext:
        #  runAsNonRoot: true
        #  runAsUser: 2000
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: data-volume
        - mountPath: /var/lib/mongodb-mms-automation/authentication
          name: example-mongodb-keyfile
        - mountPath: /opt
          name: mongod-conf-vol

      volumes:
        - name: mongod-conf-vol
          configMap:
            name: mongod-conf
            items:
            - key: automation-mongod.conf
              path: automation-mongod.conf
        - name: data-volume
          persistentVolumeClaim:
            claimName: standalone-mongodb-1-pvc

        - name: example-mongodb-keyfile
          secret:
            secretName: mongo-key
            defaultMode: 384
