apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ required "mongodb.namespace is required in chart values" .Values.mongodb.namespace }}
  name: standalone-mongodb-arbiter-pvc

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: mongodb-xfs
